### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'users'

### ISSUE THREAD

**Issue by cyber-urvesh** [amiryousefi/telegram-analysis#1] opened 2019-08-19 14:30 UTC
When I execute the following command:

`python3 ChannelUsers.py `
It gives the following error: 

ChannelUsers.py:30: RuntimeWarning: coroutine 'UserMethods.is_user_authorized' was never awaited
  if not client.is_user_authorized():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
enter entity(telegram URL or entity id):Web HackZ
Traceback (most recent call last):
  File "ChannelUsers.py", line 57, in <module>
    if not participants.users:
AttributeError: 'coroutine' object has no attribute 'users'
sys:1: RuntimeWarning: coroutine 'UserMethods.get_me' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'UserMethods.__call__' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
sys:1: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Also please tell, exactly what is Entity Id or Telegram URL ? What are we supposed to write for that parameter.

**Comment by pdelteil** [comment] 2019-11-01 17:00
Same issue here!

**Comment by pdelteil** [comment] 2019-11-01 17:05
I fixed it adding this import:

import telethon.sync

**Comment by amiryousefi** [comment] 2019-11-01 18:18
Thank you @pdelteil 
I'll give it a try and add it to the code.
Also, if you make a pull request I can merge it with the master 👍

**Comment by k-oktavius** [comment] 2019-12-08 09:59
Hi,
the same error happened to me and unfortunately importing telethon. sync didn't help.
do you have any other solution?
I have searched the web to find a solution but found any.

**Comment by deraswer** [comment] 2020-01-03 19:40
Check my pull-request, plz. It solve this issue very well

**Comment by amiryousefi** [comment] 2020-01-05 11:45
Thanks to @deraswer pull request(https://github.com/amiryousefi/telegram-analysis/pull/4), the issue is now solved.
It is merged into master.

**Closed as completed by amiryousefi** 2020-01-05 11:45 UTC
Labels: bug

**Comment by Keramatfar** [comment] 2020-02-15 11:57
> import telethon.sync

does not work.

**Comment by devendrachandora** [comment] 2020-04-11 10:59
New File also does not Work

**Comment by xectrone** [comment] 2021-07-12 13:24
> > import telethon.sync
> 
> does not work.

nope :(
